### ISSUE TITLE
[Enhancement] some ideas!

### ISSUE THREAD

**Issue by Looodon** [Witixin1512/WanderingFighters#2]
hey,
Great mod, i've been looking for a mod like this! I was wondering if you'll consider adding a config option to 
1) change how much damage the wandering traders inflict so it's not instant kill
2) turning on/off the wandering trader camps
Have a nice day!

**Comment by Witixin1512** [comment]
Hello!
1. Is done!
and 2 is easily doable by using a datapack and making the list of biomes this can spawn in be empty!
Thank you!

**Comment by Witixin1512** [comment]
- Separated the modifiers
- Not letting you tame the llamas is intentional
- They shouldnt attack you while in creative.

**Comment by Witixin1512** [comment]
Whoops, my bad, forgot to actually make the change, pushing a fixed build now. Also added a config for rapid fire spit
