### ISSUE TITLE
Mod File wanderingfighters-1.19-forge-1.2.0.jar needs language provider javafml:44 or above to load

### ISSUE THREAD

**Issue by boris2255** [Witixin1512/WanderingFighters#4]
im currently playing on minecraft 1.19.2, found the mod in curseforge and it appears to not have been updated for 1.19.2 is it possible for you to do that?

**Comment by boris2255** [comment]
it is listed as a 1.12.2 mod and it appears as such in the curseforge app

**Comment by Witixin1512** [comment]
![image](https://user-images.githubusercontent.com/73248264/210659016-9ed8649a-e158-4c17-8e2e-c32334307fe2.png)
The mod is listed as 1.19.3. Always has.
