### ISSUE TITLE
Can't get on Minecraft

### ISSUE THREAD

**Issue by Looodon** [Witixin1512/WanderingFighters#5]
The latest version of the mod wont let me get on Minecraft.

![2023-01-04 13_27_43](https://user-images.githubusercontent.com/111690606/210653166-473e2e67-4b0f-4c3c-83f5-1489d6f144f7.png)

**Comment by Witixin1512** [comment]
![image](https://user-images.githubusercontent.com/73248264/210659040-2947eb1f-f368-4357-ba41-71648ce73f75.png)
Nope, the mod is marked as 1.19.3

**Comment by Witixin1512** [comment]
Latest only supports that, if you need 1.19.2, go older
