### ISSUE TITLE
configuable drops?

### ISSUE THREAD

**Issue by Aceplante** [Witixin1512/WanderingFighters#7]
Despite the loot modifier saying 23, they sometimes drop over a stack of emeralds. How would I go about fixing this? Perhaps the amount can be configurable?

I also feel like that have too much health. Can that also be configurable?

**Comment by Witixin1512** [comment]
Apologies for the wait, this has been a bug on my side.
Health has been configurable for a while using the config.

As for the emerald amount, the Trader was also dropping the cost of the emeralds in the inputs of the trades. This has been corrected, they will only drop the output of the trades, as long as you haven't bought all of the stock of that trade.
