### ISSUE TITLE
Please add an option to disable WanderingShopStructure spawn in world

### ISSUE THREAD

**Issue by ColdTearsYY** [Witixin1512/WanderingFighters#8]
Hello and I appreciate your work in this wonderful mod. Could you add an option to disable WanderingShopStructure spawn in world ?

**Comment by Witixin1512** [comment]
This is something you can do already using a datapack,by supplying a `code_wandering_shop.json` file to remove the structure from the structure set file.

The new file, located under `data/wanderingfighters/worldgen/structure_set/code_wandering_shop.json` would look like this:

```json
{
  "structures": [
  ],
  "placement": {
    "type": "minecraft:random_spread",
    "salt": 1358829105,

    "spacing": 32,

    "separation": 16
  }
}
```

I have no plans to disable the spawning of the structure by default.
