### ISSUE TITLE
Broken on 1.20.1?

### ISSUE THREAD

**Issue by Looodon** [Witixin1512/WanderingFighters#9]
Hey, 
For some reason on Minecraft version 1.20.1 (forge) when you kill the wandering trader he drops all of the items in his trade menu which is extremely broken. I can't have it in my modpack anymore because I have custom trades which aren't meant to be dropped

**Comment by Witixin1512** [comment]
While this behaviour is intentional, I've added a config option to disable the drops added by this mod to Wandering Traders.
Additionally, using a datapack you can modify the loot modifier added by this mod so that only aggressive Wandering Traders drop their shop as a reward for fighting them.
